# ofn.conf
# configuration file for Oracle Free Now

[OFN]
ofndata=/opt/oracle/ofndata
ofnlog=/opt/oracle/ofndata/log
ofnrun=/var/run/ofn

[BACKUP]
bkupdst=/opt/oracle/ofndata/backup
bkuptype=rman      # backup type [ rman | dp ]
bkuplvl=incr       # backup type for daily [ incr | full ]
bkupfday=sun       # day of week to do full backup
bkuptime=01:00     # time of day to do backup
bkuparcf=2         # freqauency in hours to backup archive logs
bkuprtn=14         # backup retntion in days
# optional parameters
bkupcomp=T         # compress backups [ T | F ]
bkupsecsiz=500M    # backup section size for RMAN only 500M = MB
bkupfilesperset=   # number of archivelog files per backupset piece

[GENERAL]
oratab=/etc/oratab
orainst=/etc/oraInst.loc
dbsid=FREE
dbpdb=FREEPDB1

[LOCATIONS]
db_tns=/opt/oracle/oradata/dbconfig/FREE
db_admin=/opt/oracle/admin
db_home=/opt/oracle/product/23ai/dbhomeFree

