# ofn.conf
# configuration file for Oracle Free Now

[OFN]
ofnbase=/opt/ofn
ofndata=/opt/oracle/ofndata
ofnlog=/opt/oracle/ofndata/log
ofnrun=/run/ofn

[BACKUP]
bkupdst=/opt/oracle/ofndata/backup
bkuptype=rman      # backup type [ rman | dp ]
bkuplvl=incr       # backup type for daily [ incr | full ]
bkupfday=sun       # day of week to do full backup
bkuptime=01:00     # time of day to do backup
bkuparcf=2         # freqauency in hours to backup archive logs
bkuprtn=14         # backup retntion in days
# optional parameters
bkupcomp=T         # compress backups [ T | F ]
bkupsecsiz=500M    # backup section size for RMAN only 500M = MB
bkupfilesperset=   # number of archivelog files per backupset piece

[GENERAL]
oracle_base=/opt/oracle
oratab=/etc/oratab
orainst=/etc/oraInst.loc
dbsid=FREE
dbpdb=FREEPDB1
lsnr_port=1521

[LOCATIONS]
db_tns=/opt/oracle/oradata/dbconfig/FREE
db_admin=/opt/oracle/admin
db_home=/opt/oracle/product/23ai/dbhomeFree
db_data=            # defaults to /opt/oracle/oradata
db_arch=/opt/oracle/oraarch

[ORDS]
open_java=java-21-openjdk
ords_addrpm=lsof
ords_path=/opt/oracle/product/ords
ords_port=8443
ords_admin=/opt/oracle/admin/ords
ords_repo=https://yum.oracle.com/repo/OracleLinux/OLX/oracle/software/x86_64
ords_latest=https://download.oracle.com/otn_software/java/ords/ords-latest.zip

